### PR TITLE
Remove ghc-core-smallstep from Hackage

### PR DESCRIPTION
**Pull request by mark-stopka**

### CODE REVIEW

**Comment by mark-stopka** [comment]
@peti, @mimi1vx ready for merge... should I `osc rm` from `devel:languages:haskell` afterwards?

**Comment by mimi1vx** [comment]
why remove?

**Comment by peti** [comment]
@mark-stopka, I'm not sure whether this is obvious, so just in case let me mention that packages you add to these projects typically go into `openSUSE:Factory`. Adding a package there causes quite a bit of work for several people:

1. Ondrej and I have to maintain the package and make sure that it keeps building even it's dependencies are updated, etc.
2. The openSUSE Review Team must go through our submissions every time we change something and make sure that all formal criteria (like changelogs) are met.
3. Once the review has passed, another group of people must do integration tests to ensure that our changes don't affect anything else in Tumbleweed. If it turns out there are problems, then we have to go back to step (1) to fix the issue and repeat that process.
4. New submissions have their licenses and source code reviewed by a lawyer.

Basically, adding a package here and submitting it to Factory is *not* a trivial matter.

Now imagine what all these volunteers feel when we add a package to Factory and then, a week later, remove it again. My guess is that everyone feels like their time has been wasted and that the package should not have been added in the first place.

Therefore I would like to encourage you to slow down the pace. You've added a LOT of packages to the distribution now, and I would like to make sure that all of these additions are actually required and useful in some way, because otherwise we are wasting our time. 

Would you mind formulating some kind of goal that you would like to accomplish? Why are you adding these packages? What is the end you would ultimately like to achieve with these packages in openSUSE?

**Comment by mark-stopka** [comment]
The end goal is to have all packages in https://build.opensuse.org/project/show/devel:languages:haskell:cardano build agains openSUSE_Tumbleweed_pure target. This was a mistake I made due to being new to the Haskell development environment, but I am quite certain, that all others are not.

It was a poolry chosen naming convention for the IOG / Hackage package so I confiused the two, basically rule of thumb shoul be - is it a Hackage dependency - it is in Factory, is it IOG or some "other 3rd party" package it should be in :cardano subproject.

**Comment by peti** [comment]
My preferred work flow would be to create a `cardano` package set in `cabal2obs` that we can use to populate all those dependencies into the `devel:languages:haskell:cardano` project. In that project, we can do whatever we please (like adding or removing entries) without affecting anyone else. Once that project is stable, we can move everything to Tumbleweed. OK?

**Comment by mark-stopka** [comment]
That sure works for me, we can add the `network-mux` dependencies using `cabal2obs` to `devel:languages:haskell:cardano`, I however don't know what changes are required to be made...

**Comment by mark-stopka** [comment]
I changed the buuild targets from x86 openSUSE Tumbleweed, they build against this automated GitHub repo now, so we can slow-down the `copypac` from the GHC dev sub-projects to `:haskell`

image

**Comment by peti** [comment]
Everything in `devel:languages:haskell:ghc-8.10.x` is copied to `devel:languages:haskell` *automatically* once per day, and everything that is in `devel:languages:haskell` will be submitted to `openSUSE:Factory` at least once per week. Therefore, this solution doesn't really work. The packages you want to add have to go directly into `devel:languages:haskell:cardano` (or something similar) if we want to avoid submitting everything to Factory right away.

**Comment by mimi1vx** [comment]
@peti we have daily sync between ghc-8.10.x ? I thought  we sync only in tuesday or manually?

**Comment by peti** [comment]
> @peti we have daily sync between ghc-8.10.x ? I thought we sync only in tuesday or manually?

Yes, the sync happens every night (unless there are build errors).

**Comment by mimi1vx** [comment]
this package if now builds fine on ghc-8.10.x so --> keep in 8.10.x set and remove from 9.0 where it fails horribly
wheen we move to new ghc --> delete request from factory

**Comment by peti** [comment]
Why should we submit this package to factory when (a) nobody needs it and (b) we already know that it will be broken soon and we'll have to remove it?

I think it's better to not submit it in the first place.

**Comment by mark-stopka** [comment]
I agree with @peti here, we should get this package out of the OBS projects ASAP, it was an unfortunate name collision I have not noticed, I will be more diligent moving forward.

**Pull request closed without merging**
