### PR TITLE
Add bimap from Hackage

### PR DESCRIPTION
**Pull request by mark-stopka**

### CODE REVIEW

**Comment by mark-stopka** [comment]
Failing job related to changes made by @peti affecting whole repo CI status...

**Comment by mark-stopka** [comment]
@peti, @mimi1vx also ready for merge... The #45 will take much re-factoring to make today merge window... But I will very much appreciate this being merged, I missed the name and thought it's `bitmap`, which was already present, so this a missing dependency for `ghc-goblins` [GitHub](https://github.com/input-output-hk/goblins), - Genetic Algorithm based randomized testing library from IOG...

**Comment by mark-stopka** [comment]
@mrBliss, are ypu planning to do versioned releases of `goblins`?

**Comment by mrBliss** [comment]
> @mrBliss, are ypu planning to do versioned releases of `goblins`?

This is more a question for @nc6, as `goblins` is only used by the ledger team, not the consensus team. Nevertheless, the package is no longer in active development and I'm not aware of any plans to release it.

BTW, I would expect that `goblins` is only needed if you are building the testsuite of `cardano-node` (and/or its dependencies). If you only build the executable and not any testsuites, you'll need fewer packages and your build will speed up significantly.

**Comment by mark-stopka** [comment]
We plan to have a CI as part of our release cycle, so we will need these test dependencies also... perhaps if it is "finished" version, it could be published on Hackage for everyone to use...

**Pull request merged**
